### ISSUE TITLE
lcmgl.text causes director to exit

### ISSUE THREAD

**Issue by wxmerkt** [RobotLocomotion/director#313]
``` matlab
lcmgl.text(zeros(3,1),'test',0,0)
lcmgl.switchBuffers
```

causes director to close instantaneously with:

```
freeglut  ERROR:  Function <glutBitmapHeight> called without first calling 'glutInit'.
```

**Comment by patmarion** [comment]
I think you can edit director's main file (src/app/main.cpp) and add a call to glutInit after including the glut header.  It might fix this crash.  Otherwise, text rendering isn't supported.

https://www.opengl.org/resources/libraries/glut/spec3/node10.html

You could also try faking the argc/argv values and adding the call to glutInit to the vtkLCMGLProp.cxx constructor.

<pre>
char *myargv [1];
int myargc=1;
myargv[0]=strdup("director");
glutInit(&myargc, myargv);
</pre>
