### ISSUE TITLE
Running precompiled binaries on 16.04

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/director#352]
Should the linux binaries work on 16.04? Ref: https://github.com/rdeits/DrakeVisualizer.jl/issues/7

**Comment by patmarion** [comment]
copy n pasted comment from other  thread:

Sorry, I don't expect the binaries to work anywhere except Ubuntu 14, since these binaries have system dependencies.  I can do two things:

  - package vtk with director
  - use travis-ci's ubuntu 16 image (I assume this exists?) to provide director packages for ubuntu 16

**Comment by rdeits** [comment]
Sorry, wasn't sure if you would get pinged in a thread from my repo. I'm closing the duplicate.
