### ISSUE TITLE
Citation information/guidance

### ISSUE THREAD

**Issue by iamwolf** [RobotLocomotion/director#43]
@patmarion Do you have a pre-prepared bibtex snippet on how to best cite the director? And would you like to add this citation information to the readme?

Thanks,
Wolf

**Comment by patmarion** [comment]
No, I don't have bibtex for citing the director.  The closest thing that has been published might be the JFR paper on affordance based planning.

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=BqV8LaoAAAAJ&citation_for_view=BqV8LaoAAAAJ:Zph67rFs4hoC

If you'd like to cite the source code, perhaps a cite to the github url?

**Comment by cdarpino** [comment]
I encourage you to have one recommended citation form for the Director (I'll use it). For example, Drake has the following:

>>    Citing Drake:
    If you would like to cite Drake in your academic publications, we suggest the following BibTeX citation:
    @misc{drake,
    author = "Russ Tedrake",
    title = "Drake: A planning, control, and analysis toolbox for nonlinear dynamical systems",
    year = 2014,
    url = "http://drake.mit.edu"
   }

I think you can do something similar using the github link.

**Comment by patmarion** [comment]
Following the drake style citation, it could be:

<pre>

@misc{director,
author = "Pat Marion",
title = "Director: A robotics interface and visualization framework",
year = 2015,
url = "http://github.com/RobotLocomotion/director"
}

</pre>

I don't like that the citation gives me sole credit for the software since it has seen many contributors, but it's fair to say I am the primary author and maybe in the future there will be a paper to cite that could be used to update this.  What do you guys think?

**Comment by cdarpino** [comment]
In my view this works well! I'll be happy to use it.
It can be augmented when the paper is out (keeping the url).
Also, the git history shows the contributions.

**Comment by RussTedrake** [comment]
I feel the same about drake.  It made more sense when i posted it, but now feels silly.
